zephyrproject-rtos/hal_ti

- simplelink/source/ti/devices/cc13x2_cc26x2/CMakeLists.txt
Required for RFCDoorbellSendTo used in 802.15.4 driver.
See zephyrproject-rtos/zephyr#16263
Signed-off-by: Brett Witherspoon <spoonb@cdspooner.com>
> simplelink: add RFC driverlib sources

- simplelink/CMakeLists.txt
Originall this was included directly in the driver (from ext/), fix this
to allow inclusion from the module.
Signed-off-by: Anas Nashif <anas.nashif@intel.com>
> simplelink: include needed headers

- simplelink/source/ti/devices/msp432p4xx/startup_system_files/system_msp432p401m.c
- simplelink/source/ti/devices/msp432p4xx/startup_system_files/system_msp432p401r.c
- simplelink/source/ti/devices/msp432p4xx/startup_system_files/system_msp432p4111.c
- simplelink/source/ti/devices/msp432p4xx/startup_system_files/system_msp432p411v.c
- simplelink/source/ti/devices/msp432p4xx/startup_system_files/system_msp432p411y.c
Needed for https://github.com/zephyrproject-rtos/zephyr/pull/20757, to
avoid a warning-turned-error.
> dts: Include devicetree.h instead of generated_dts_board.h

- simplelink/CMakeLists.txt
- simplelink/README
- simplelink/kernel/zephyr/dpl/ClockP_zephyr.c
- simplelink/kernel/zephyr/dpl/HwiP_zephyr.c
- simplelink/kernel/zephyr/dpl/QueueP.h
- simplelink/kernel/zephyr/dpl/QueueP_zephyr.c
- simplelink/kernel/zephyr/dpl/SemaphoreP_zephyr.c
- simplelink/kernel/zephyr/dpl/SwiP_zephyr.c
- simplelink/kernel/zephyr/dpl/config.c
- simplelink/kernel/zephyr/dpl/stubs.h
- simplelink/source/ti/drivers/dpl/ClockP.h
- simplelink/source/ti/drivers/rf/RF.h
- simplelink/source/ti/drivers/rf/RFCC26X2_multiMode.c
This PR imports the TI RF driver from SimpleLink SDK 3.10.00.53, and implements the functions needed in the DPL (ClockP, SemaphoreP, HwiP and SwiP) to support the driver.
> RF driver support

- simplelink/kernel/zephyr/dpl/SemaphoreP_zephyr.c
When creating or constructing a semaphore, the count passed in is
incorrectly being ignored. We need to fix SemaphoreP_create/construct
to pass the initial count to k_sem_init().
Signed-off-by: Vincent Wan <vincent.wan@linaro.org>
> simplelink: dpl: Fix SemaphoreP initialization

- simplelink/source/ti/drivers/net/wifi/porting/cc_pal.h
Remove hacks that were introduced when it was not possible to include
this header earlier, and directly include the header from Zephyr. This
would allow new changes (such as the recent change to modify
clock_gettime() into a syscall) to be reflected in the HAL.
Signed-off-by: Vincent Wan <vincent.wan@linaro.org>
> simplelink: drivers: wifi: include proper posix/time.h from Zephyr

- simplelink/source/ti/devices/msp432p4xx/startup_system_files/system_msp432p401m.c
- simplelink/source/ti/devices/msp432p4xx/startup_system_files/system_msp432p401r.c
- simplelink/source/ti/devices/msp432p4xx/startup_system_files/system_msp432p4111.c
- simplelink/source/ti/devices/msp432p4xx/startup_system_files/system_msp432p411v.c
- simplelink/source/ti/devices/msp432p4xx/startup_system_files/system_msp432p411y.c
Replace DT_ARM_CORTEX_*_0_CLOCK_FREQUENCY with a PATH based reference
to cpu@0 (DT_PATH(cpus, cpu_0)) and than getting the clock_frequency
property:
DT_ARM_CORTEX_*_CLOCK_FREQUENCY ->
DT_PROP(DT_PATH(cpus, cpu_0), clock_frequency)
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
> msp432p4xx: replace DT_ARM_CORTEX_*_CLOCK_FREQUENCY with new dt macros

- simplelink/source/ti/devices/cc13x2_cc26x2/CMakeLists.txt
Adding some files to the build that are necessary in order to rebuild the IEEE 802.15.4 driver. rfc.c was inadvertently left out during the update to SimpleLink SDK 4.10, and a new patch file has also been introduced.
> Add files necessary to rebuild Zephyr's IEEE 802.15.4 driver

- simplelink/kernel/zephyr/dpl/ClockP_zephyr.c
Convert to use C99 types as we intend to deprecate the zephyr
specific integer types.
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
> simplelink: dpl: Convert from Zephyr to C99 types

- simplelink/CMakeLists.txt
CC: @vanti 
RFCC26X2_multiMode.c references Temperature_getTemperature() but source/ti/drivers/temperature/TemperatureCC26X2.c was not previously linked in.
> simplelink: drivers: resolve symbol Temperature_getTemperature

- simplelink/CMakeLists.txt
- simplelink/kernel/zephyr/dpl/dpl.c
- simplelink/source/ti/drivers/net/wifi/slnetif/slnetifwifi.c
- simplelink/source/ti/net/slnet.h
- simplelink/source/ti/net/slneterr.h
- simplelink/source/ti/net/slnetif.c
- simplelink/source/ti/net/slnetif.h
- simplelink/source/ti/net/slnetsock.c
- simplelink/source/ti/net/slnetsock.h
- simplelink/source/ti/net/slnetutils.c
- simplelink/source/ti/net/slnetutils.h
Bring in SlNetSock and its associated modules from the TI CC32xx
SimpleLink SDK 4.10.00.07, with some minor tweaks to the SlNetSock
code to avoid errors/warnings when building for Zephyr, due to its
stricter build flags and its idiosyncrasies around its posix
implementations.
> Add SlNetSock modules

- simplelink/kernel/zephyr/dpl/dpl.c
All device objects are const-qualified; update the init function
signature to be compatible.
Signed-off-by: Peter A. Bigot <pab@pabigot.com>
> simplelink: dpl: update for Zephyr API change

- simplelink/kernel/zephyr/dpl/HwiP_zephyr.c
IRQ_CONNECT() requires that all parameters be known at compile-time, but
that is not the case with the interrupt priority. Instead, use
irq_connect_dynamic() which allows runtime arguments.
Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>
> dpl: Use dynamic interrupt binding

- simplelink/source/ti/drivers/power/PowerCC26X2.c
The constraints API offered by TI HAL is meant to be used externally,
for example, when implementing a policy using their policy mechanism
(not used on Zephyr). The API is likely designed for systems where a
thin RTOS is used (e.g., FreeRTOS, TI-RTOS?), places where you basically
get a Kernel and a few services around, but not a system like Zephyr
where you also get, for example, a power management subsystem. This
means that it gets difficult for an RTOS like Zephyr to use such HAL
APIs while using its own constraints API. The first question is why we
allowed such kind of HAL code to be part of upstream Zephyr. It
certainly does useful things, but it is also uses a HAL infrastructure
which is hardly exportable to an RTOS like Zephyr. Part of the
Power_init() code, for example, should …
> hal: drivers: use Zephyr PM constraints API

- simplelink/source/ti/drivers/power/PowerCC26X2.c
The API has changed to:
pm_constraint_set: pm_policy_state_lock_get
pm_constraint_release: pm_policy_state_lock_put
> hal: drivers: update Zephyr constraints API

- simplelink/source/ti/drivers/net/wifi/porting/cc_pal.h
- simplelink/source/ti/net/slnetsock.h
Instead of using `#include <posix/time.h>`, just use `#include <time.h>`.
Required-by zephyrproject-rtos/zephyr#43998
> zephyr: remove posix prefix on time.h standard include

- simplelink/source/ti/drivers/power/PowerCC26X2.c
Use new pm_policy_state_lock_get() and pm_policy_state_lock_put()
functions.
This is for https://github.com/zephyrproject-rtos/zephyr/pull/44637
> hal: drivers: Use new state lock API.

- simplelink/kernel/zephyr/dpl/dpl.h
Use the C library errno header instead of assuming a particular
implementation. This allows the use of picolibc with projects
using this module.
Signed-off-by: Keith Packard <keithp@keithp.com>
> simplelink: Use <errno.h> to get definition of errno

- simplelink/source/ti/drivers/power/PowerCC26X2.c
Zephyr has prefixed all of its includes with <zephyr/...>. While the old
mode can still be used (CONFIG_LEGACY_INCLUDE_PATH) and is still enabled
by default, it's better to be prepared for its removal in the future.
> power: migrate PM includes to <zephyr/...>

- simplelink/kernel/zephyr/dpl/ClockP_zephyr.c
- simplelink/kernel/zephyr/dpl/HwiP_zephyr.c
- simplelink/kernel/zephyr/dpl/MutexP_zephyr.c
- simplelink/kernel/zephyr/dpl/SemaphoreP_zephyr.c
- simplelink/kernel/zephyr/dpl/SwiP_zephyr.c
- simplelink/kernel/zephyr/dpl/config.c
- simplelink/kernel/zephyr/dpl/dpl.c
- simplelink/kernel/zephyr/dpl/stubs.h
- simplelink/source/ti/devices/cc13x2_cc26x2/startup_files/ccfg.c
- simplelink/source/ti/devices/msp432p4xx/startup_system_files/system_msp432p401m.c
- simplelink/source/ti/devices/msp432p4xx/startup_system_files/system_msp432p401r.c
- simplelink/source/ti/devices/msp432p4xx/startup_system_files/system_msp432p4111.c
- simplelink/source/ti/devices/msp432p4xx/startup_system_files/system_msp432p411v.c
- simplelink/source/ti/devices/msp432p4xx/startup_system_files/system_msp432p411y.c
- simplelink/source/ti/drivers/dpl/ClockP.h
- simplelink/source/ti/drivers/net/wifi/porting/cc_pal.h
- simplelink/source/ti/net/slnetsock.c
Zephyr has prefixed all of its includes with <zephyr/...>. While the old
mode can still be used (CONFIG_LEGACY_INCLUDE_PATH) and is still enabled
by default, it's better to be prepared for its removal in the future.
> zephyr: update include paths to use <zephyr/...>

- simplelink/source/ti/devices/cc13x2_cc26x2/CMakeLists.txt
These sources are required for CC13xx/CC26xx on-chip flash driver which makes use of TI's HAL functions and some of them are not inside ROM.
> simplelink: cc13x2_cc26x2: include flash driverlib sources

- simplelink/CMakeLists.txt
- simplelink/kernel/zephyr/dpl/config.c
- simplelink/source/ti/devices/cc13x2_cc26x2/CMakeLists.txt
Required for supporting CC13x2P / CC26x2P (with high power amplifier) variants:
- conditions for new `SOC_CC1352P` / `SOC_CC2652P` kconfig defines;
- new condition to be able to supply a custom `RFCC26XX_hwAttrs` (to be able to add event callback required for board-specific antenna switching).
Will come with pull req using these to support CC1352P Launchpad board with power amplifier (for IEEE802152 Sub-GHz driver).
> cc13x2: kconfig conditions for P variant support & custom RF hwattrs

- simplelink/CMakeLists.txt
- simplelink/kernel/zephyr/dpl/config.c
- simplelink/source/ti/devices/cc13x2_cc26x2/CMakeLists.txt
The TI HAL requires certain definitions, e.g. DeviceFamily_XYZ to be
present when compiling, as some public headers require them. Instead of
manually injecting them to every file because one of its includes
requires it, just insert global level definitions. This makes sure
they'll be made available where necessary without the need of individual
hacks.
Signed-off-by: Gerard Marull-Paretas <gerard.marull@nordicsemi.no>
> hal: inject required definitions

- simplelink/source/ti/devices/cc13x2_cc26x2/CMakeLists.txt
To be used by upcoming TI CC13xx/CC26xx Zephyr ADC driver (PR incoming).
> simplelink: cc13x2_cc26x2: include ADC driverlib sources

- simplelink/kernel/zephyr/dpl/stubs.h
- simplelink/source/ti/drivers/dpl/ClockP.h
<zephyr/zephyr.h> is just a shim to <zephyr/kernel.h>.
Signed-off-by: Gerard Marull-Paretas <gerard@teslabs.com>
> hal: use s/<zephyr/zephyr.h>/<zephyr/kernel.h>

- simplelink/source/ti/drivers/net/wifi/source/driver.h
The normative spec says this returns `pthread_t`, not `void *`.
It's probably better to simply `#include <pthread.h>` outside of this file explicitly (due to current non-standard prefixed path in Zerphy) than to re-declare it with a potentially conflicting signature.
> simplelink: wifi: avoid re-declaring pthread_self()

- simplelink/kernel/zephyr/dpl/dpl.c
Picolibc doesn't always use an __errno function, preferring to use TLS errno variable instead as that's more efficient. But, that means applications shouldn't dig through the original errno abstraction to use the underlying implementation directly.
Signed-off-by: Keith Packard <keithp@keithp.com>
> simplelink: use 'errno' instead of '*__errno()' for picolibc compat

- simplelink/source/ti/drivers/rf/RFCC26X2_multiMode.c
The fix of a race condition in the previous commit introduced a regression in power management which disallowed transitions to power-down state. This fixes the regression.
@vaishnavachath Sorry for that. :-( It's just a two-liner so probably a quick review.
@cfriedt Could you maybe do a second review? This is a quick one.
> drivers: rf: RFCC26X2_multiMode: regression due to prior race fix

- simplelink/kernel/zephyr/dpl/ClockP_zephyr.c
- simplelink/kernel/zephyr/dpl/HwiP_zephyr.c
- simplelink/kernel/zephyr/dpl/SemaphoreP_zephyr.c
- simplelink/kernel/zephyr/dpl/config.c
- simplelink/kernel/zephyr/dpl/stubs.h
- simplelink/source/ti/drivers/apps/Button.c
- simplelink/source/ti/drivers/apps/LED.c
- simplelink/source/ti/drivers/dpl/ClockP.h
- simplelink/source/ti/drivers/net/wifi/porting/user.h
- simplelink/source/ti/drivers/power/PowerCC26X2.c
- simplelink/source/ti/drivers/rf/RFCC26X2_multiMode.c
- simplelink/source/ti/drivers/sd/SDSPI.c
- simplelink/source/ti/drivers/uart/UARTCC32XXDMA.c
This change set contains fixes for several issues discovered in Zephyr's ClockP API implementation:
* the unused stubs.h header was removed.
* the ClockP implementation contained some cruft due to an incomplete migration from the ms based to the tick based kernel timer API.
* the ClockP implementation assumed timeouts and periods to be given in ms although TI's API always expected ticks.
This change set contains a fix for a major conversion bug in TI's own usage of the ClockP API throughout the SimpleLink framework:
* The TI clock subsystem has a method ClockP_getSystemTickPeriod()  that is used in many places as a multipler to convert ticks from/to microseconds or milliseconds. This function returns integer us-precision values. OSes like Zephyr but also the original nortos, FreeRTOS and …
> Fix: Several TI clock issues

- simplelink/source/ti/net/slnetsock.h
This include is causing a nemspace collision between the picolibc and the Zephyr select definitions. Looks like this was originally a '#ifndef CONFIG_NET_SOCKETS_POSIX_NAMES' but got inverted as a positive condition at some stage, which is now causing a build fail.
> simplelink: slnetsock: fix sys/time.h include when sockets are enabled

- simplelink/CMakeLists.txt
- simplelink/source/ti/devices/DeviceFamily.h
The "DeviceFamily" defines are not generated for the CC26x2x7 family of parts.
Added the CMakeLists.txt, etc definitions in the pattern of the CC13x2x7 family.
Also add DeviceFamily_CC13X2X7 to DeviceFamily multiple select macro.
> Add SOC_CC2652{R,P}7 to DeviceFamily if-tree

- simplelink/source/ti/devices/cc13x2x7_cc26x2x7/CMakeLists.txt
- `AUXADCEnableSync` does not seem to be present in ROM and thus we need to add this file.
- Tested on beagleconnect freedom
> simplelink: ti: devices: Add ADC support

- dts/ti/mspm0/l/mspm0l222x-pinctrl.dtsi
Added input-enable property to all UART RX pin entries across the
MSPM0L222x pinctrl file to ensure proper input functionality for UART
reception on all supported RX pins.
Signed-off-by: Sanjay Vallimanalan <sanjay@linumiz.com>
> dts: ti: mspm0: Enable input for all UART RX pins

- simplelink/source/ti/net/slnetsock.h
Previously, the header `<ti/net/slnetsock.h>` was forward-declaring a typed struct depending on deprecated and nonexistent Kconfig options. This caused a compile error when building `sample.net.sockets.http_get.offload.simplelink` because struct timeval was not defined in a non-standard header.
https://github.com/zephyrproject-rtos/zephyr/actions/runs/17698392922/job/50300874059?pr=95939
Since the offload driver must exist whether or not the applciation has enabled POSIX, and struct timeval is POSIX, simply define the SlNetSock_Timeval_t typed structure whether or not POSIX is enabled using ANSI/ISO C types.
In this case, `long` was chosen to match the wordsize of whatever architecture is being built.
> net: slnetsock: do not require posix to define SlNetSock_Timeval_t
